config/routes.rb
SampleApp::Application.routes.draw do

  get "comments/create"

  get "comments/destroy"

  resources :posts do
    resources :comments
  end
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match 'classes/cs4413',  :to => 'static_pages#cs4413'
  root :to => "pages#home"

end

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="block">
    	<p>Copyright &copy; <%= Time.now.year %> CSedu.</p>
    </div> 
    <div id="main-navigation">
    	<ul class="wat-cf">
    		<li><%= link_to "About", about_path %></li>
    		<li><%= link_to "Contact", contact_path %></li>
    		<li><%= link_to "News", 'http://www.sciencedaily.com/news/computers_math/computer_science/' %></li>
    	</ul>
    </div>
</div>

app/views/layouts/_footer.html.erb.old.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", 'http://news.railstutorial.org/' %></li>
      <li><%= link_to "Rails Tutorial", 'http://railstutorial.org/' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div id="header">
	<h1><a href="/"><%= title %></a></h1>
    <div id="user-navigation">
    	<ul class="wat-cf">
    		<% if signed_in? %>
        		<li><%= link_to "Sign out", signout_path, :class => "logout" %></li>
      		<% else %>
        		<li><%= link_to "Sign in", signin_path %></li>
      		<% end %>
    	</ul>
	</div>
    <div id="main-navigation">
    	<ul class="wat-cf">
    		<li class=<%= (params[:controller] == "pages" &&  params[:action] == "home" ? "active" : nil )%>><%= link_to "Home", root_path %></li>
      		<% if signed_in? %>
        		<li class=<%= (params[:controller] == "users" &&  params[:action] == "show" ? "active" : nil)%>>
					<%= link_to "Profile", current_user %></li>
				<li class=<%= (params[:controller] == "posts" &&  params[:action] == "show" ? "active" : nil)%>>
					<%= link_to "Posts", posts_path %></li>
        		<li class=<%= (params[:controller] == "users" &&  params[:action] == "index" ? "active" : nil)%>>
					<%= link_to "Users", users_path %></li>
        		<li class=<%= (params[:controller] == "users" &&  params[:action] == "edit" ? "active" : nil)%>>
					<%= link_to "Settings", edit_user_path(current_user)%></li>
      		<% end %>
      		<li class=<%= (params[:controller] == "pages" &&  params[:action] == "help" ? "active" : nil)%>><%= link_to "Help", help_path %></li>
    	</ul>
    </div>
</div>  

app/views/layouts/_header.html.erb.old.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path %></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class="block">
          <h3>Simple Block</h3>
          <div class="content">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          </div>
        </div>

app/views/layouts/_sides.html.erb
	<div class="block">
		<h3>Classes </h3>
			<ul class="navigation">
				<li><a href="classes/cs4413" >Web Technology</a></li>
				<li><a href="#" >Computer and Information Security</a></li>
				<li><a href="#" >System Programming</a></li>
				<li><a href="#" >Programming Languages</a></li>
				<li><a href="#" >List All</a></li>
			</ul>
	</div>
	<div class="block">
		<h3>Languages </h3>
		<ul class="navigation">
			<li><a href="#" >C++/C</a></li>
			<li><a href="#" >Java</a></li>
			<li><a href="#" >PHP</a></li>
			<li><a href="#" >Ruby on rails</a></li>
			<li><a href="#" >SQL</a></li>
			<li><a href="#" >Perl</a></li>
			<li><a href="#" >List All</a></li>
		</ul>
	</div>

app/views/layouts/_sides.html.erb.old.erb
	<!--Left Area of the page -->
	<div id="leftarea" style="width: 10.6em">
	
		<div class="menubox">
				<a class="sidemenutextlive"  href=<%=root_path%> >Main Page</a>
		</div>		
		<div class="menubox">
				<a class="sidemenutextlive"  href="#" style="width: 110%">Free Tools</a>
		</div>
		<div class="menubox">
				<a class="sidemenutextlive"  href="#">Hot Topics</a>
		</div>
		<div class="menubox">
		<a class="sidemenutextlive"  href="#">News</a>
		</div>
		
		 	<hr />

	<div class="menubox" style="height: 33px">
		<a class="sidemenutextlive"  href="Classes.htm" style="width: 110%; height: 29px;" >Commandline Cheat Sheet</a>
	</div>
	<ul id="normal">
		<li><a class="sidesubmenutext" href="#" style="width: 95%">cp</a></li>
		<li><a class="sidesubmenutext" href="#"  style="width: 95%">mv</a></li>
		<li><a class="sidesubmenutext" href="#"  style="width: 95%">cat</a></li>
		<li><a class="sidesubmenutext" href="#"  style="width: 95%">nc / netcat</a></li>
		<li>
		<a class="sidesubmenutext" href="#"  style="width: 95%; margin-left: 0px;">List All</a></li>
	</ul>


 	<hr />

    <div class="menubox" style=" width: 78%">
        <a class="sidemenutext" href="#" >Sitemap</a>
    </div>

	<p>&nbsp;</p>

	<p class="center">Last Updated on<br /> 10-26-2011</p>
    <p>&nbsp;</p>

	</div>	
	<!--End Left Area -->

	<!--Right Area of the page -->
	<div id="rightarea">
	
	<div class="center">
		<form name="searchform" method="get" action="http://www.google.com" id="searchform">
        	<label for="search">
        		<input type="text" id="search" name="keywords" size="18" maxlength="140" />
        		<input type="submit" name="Search" value="Search" />
        	</label>
     	</form>
     </div>
 
 	<hr />
	
	<div class="menubox">
		<a class="sidemenutextlive"  href="Classes.htm" style="width: 105%" >Classes</a>
	</div>
	<ul id="normal">
		<li><a class="sidesubmenutext" href="#"  style="width: 95%">Web Technology</a></li>
		<li><a class="sidesubmenutext" href="#"  style="width: 95%">Computer and Information Security</a></li>
		<li><a class="sidesubmenutext" href="#"  style="width: 95%">System Programming</a></li>
		<li><a class="sidesubmenutext" href="#"  style="width: 95%">Programming Languages</a></li>
		<li><a class="sidesubmenutext" href="#"  style="width: 95%">List All</a></li>
	</ul>


 	<hr />

	<div class="menubox">
		<a class="sidemenutextlive"  href="#" style="width: 105%" >Languages</a>
	</div>
	<ul id="normal">
		<li><a class="sidesubmenutext" href="#" style="width: 95%">C++/C</a></li>
		<li><a class="sidesubmenutext" href="#" style="width: 95%">Java</a></li>
		<li><a class="sidesubmenutext" href="#" style="width: 95%">PHP</a></li>
		<li><a class="sidesubmenutext" href="#" style="width: 95%">Ruby on rails</a></li>
		<li><a class="sidesubmenutext" href="#" style="width: 95%">SQL</a></li>
		<li><a class="sidesubmenutext" href="#" style="width: 95%">Perl</a></li>
		<li><a class="sidesubmenutext" href="#" style="width: 95%">List All</a></li>
	</ul>


 	<hr />



	</div>
	<!--End Right Area -->

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'web-app-theme/base', :media => 'screen' %>
<%= stylesheet_link_tag 'web-app-theme/base',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'web-app-theme/style', :media => 'screen' %>

app/views/layouts/_stylesheets.html.erb.old.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <%= render 'layouts/header' %>
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="sidebar">
      	<%= yield (:sidebar) %>
        <%= render 'layouts/sides' %>
      </div>
      <div id="main">
        <%= yield %>
        </br>
        </br>
        <%= render 'layouts/footer' %>
    	</div>   
    </div>    
  </div>
</body>
</html>

app/views/layouts/application.html.erb.old.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <div class="wat-cf" id="wrapper">
      <div class="block">
      	<div class="content">
      	<div class="flash">
        <% flash.each do |type, message| %>
          <div class="<%= "message error" %>">
          		<%= value %>
          </div>
        <% end %>
        </div>
        </div>
        </div>
        </div>
        <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/sign.html.haml
!!!
%html
	%head
		%title My Latest Web App
		= render "layouts/stylesheets"
		= javascript_include_tag "application"
		= csrf_meta_tag
	%body
		#container
			#box
				= yield